[theme]
base = "light"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500
maxMessageSize = 500
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[mapbox]
token = ""
